'use strict';

const turretSpeech = [
    "Wheee.",
    "Wheeeeeee.",
    "I'm afraid of heights.",
    "Noooo.",
    "See you soon.",
    "I'm scared.",
    "I'm scared.",
    "Hooray.",
    "Glorious freedom.",
    "I'm flying.",
    "Goodbye.",
    "Come closer.",
    "Something's wrong.",
    "What are you doing?",
    "Failure.",
    "Ow.",
    "Oww.",
    "Owwww.",
    "It burns.",
    "I'm on fire.",
    "I'm on fire owww.",
    "Please stop.",
    "You've made your point.",
    "OK you win.",
    "This is not good.",
    "Ooohhh.",
    "Owwww.",
    "Can't...breathe.",
    "Excuse me you're squishing me.",
    "Um, hello.",
    "Help! Being squished.",
    "Good shot.",
    "Well done.",
    "I need backup.",
    "You have excellent aim.",
    "I never liked her.",
    "These things happen.",
    "That was nobody's fault.",
    "She was provoking you.",
    "Oh dear.",
    "Oh my.",
    "I blame myself.",
    "She probably deserved it.",
    "I saw it. It was an accident.",
    "She's probably OK.",
    "Noted.",
    "Hello?",
    "Hello.",
    "Target acquired.",
    "Whyyyy.",
    "I did everything you askedddd.",
    "I don't understandddd.",
    "I'm fineeee.",
    "Ahhhh.",
    "Wheee oh noooo.",
    "Whyyy.",
    "Hi.",
    "Target acquired.",
    "Dispensing product.",
    "Firing.",
    "Hello friend.",
    "Gotcha.",
    "There you are.",
    "I see you.",
    "Hellooo.",
    "Searching.",
    "Canvassing.",
    "Sentry mode activated.",
    "Is anyone there?",
    "Could you come over here?",
    "Coming through.",
    "Excuse me.",
    "Sorry.",
    "My fault.",
    "Ohh.",
    "Hello.",
    "Deploying.",
    "Preparing to dispense product.",
    "Activated.",
    "There you are.",
    "Who's there?",
    "Ahahaa.",
    "Critical error.",
    "Sorry, we're closed.",
    "Shutting down.",
    "I don't blame you.",
    "I don't hate you.",
    "Whyyyy.",
    "No hard feelings.",
    "Hey.",
    "Hey hey hey.",
    "Put me down.",
    "Woahhh.",
    "Illegal operation.",
    "Who are you?",
    "Hey.",
    "Please put me down.",
    "Help.",
    "Uh oh.",
    "Goodbye.",
    "Sleep mode activated.",
    "Your business is appreciated.",
    "Hibernating.",
    "Goodnight.",
    "Resting.",
    "Nap time.",
    "Are you still there?",
    "Target lost.",
    "Can I help you?",
    "Searching.",
    "aiaiaiaiaiai.",
    "Hey, it's me!",
    "Don't shoot!",
    "Stop shooting!",
    "Aah.",
    "Self test error.",
    "Unknown error.",
    "Malfunctioning.",
    "Aaaah.",
    "Ow ow ow ow owww.",
    "But I need to protect the humans."
  ];

  module.exports = turretSpeech;
